"""change .

Revision ID: d904b76b9811
Revises: 
Create Date: 2021-06-23 01:26:11.299960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd904b76b9811'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('desc', sa.String(length=1024), nullable=False))
    op.drop_column('item', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sa.VARCHAR(length=1024), nullable=False))
    op.drop_column('item', 'desc')
    # ### end Alembic commands ###
